#pragma once

// Display backlight (PWM)
#define YELLOW_RES_LCD_BACKLIGHT_LEDC_TIMER LEDC_TIMER_0
#define YELLOW_RES_LCD_BACKLIGHT_LEDC_MODE LEDC_LOW_SPEED_MODE
#define YELLOW_RES_LCD_BACKLIGHT_LEDC_CHANNEL LEDC_CHANNEL_0
#define YELLOW_RES_LCD_BACKLIGHT_LEDC_DUTY_RES LEDC_TIMER_8_BIT
#define YELLOW_RES_LCD_BACKLIGHT_LEDC_FREQUENCY (1000)

#define YELLOW_RES_LCD_PIN_BACKLIGHT GPIO_NUM_21

// Display
#define YELLOW_RES_LCD_PORT SPI2_HOST
#define YELLOW_RES_LCD_HORIZONTAL_RESOLUTION 240
#define YELLOW_RES_LCD_VERTICAL_RESOLUTION 320
#define YELLOW_RES_LCD_BITS_PER_PIXEL 16
#define YELLOW_RES_LCD_DRAW_BUFFER_HEIGHT (YELLOW_RES_LCD_VERTICAL_RESOLUTION / 10)
#define YELLOW_RES_LCD_DRAW_BUFFER_SIZE (YELLOW_RES_LCD_HORIZONTAL_RESOLUTION * YELLOW_RES_LCD_DRAW_BUFFER_HEIGHT * (YELLOW_RES_LCD_BITS_PER_PIXEL / 8))
#define YELLOW_RES_LCD_PIN_CS GPIO_NUM_15
#define YELLOW_RES_LCD_PIN_DC GPIO_NUM_2

